---
template_path: scratch-thermometer-managed_policy_attachable_role.template
parameters:
  Name: lambda_fetch_submission_field_role
  ManagedPolicyArns:
    - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    - !stack_output scratch-thermometer-iam/scratch-thermometer-policies/scratch-thermometer-lambda-fetch-submission-field-policy/scratch-thermometer-policy.yaml::PolicyArn
  Services:
    - lambda.amazonaws.com
