---
template_path: scratch-thermometer-iam_managed_policy.j2

sceptre_user_data:
  PolicyDocument: !file config/scratch-thermometer-iam/scratch-thermometer-policies/scratch-thermometer-apigateway-s3-thermometer-read/scratch-thermometer-policy.json

parameters:
  Name: apigateway_s3_thermometer_read_policy
