name: aws_signature_v4_interceptor
description: Dio Interceptor for AWS V4 request signing.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  aws_common: ^0.2.2
  aws_signature_v4: ^0.2.1
  dio: '>=4.0.1 <5.0.0'


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
