name: moraldistress
description: Nurse informed push sensor. Moral distress "app."
version: 0.0.2+0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: "^3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.3
  expandable_text: 2.2.0
  expansion_tile_card: ^2.0.0
  flutter_bloc: ^8.0.1
  logging: ^1.0.2
  url_launcher: ^6.0.12
  uuid: 3.0.6
  moralpainapi:
    path: ../api/dart/
  cognito_authentication_repository:
    path: packages/cognito_authentication_repository
  uva_themed_widgets:
    path: packages/uva_themed_widgets
  aws_signature_v4_interceptor:
    path: packages/aws_signature_v4_interceptor
  amplify_flutter: ^1.0.0-next.0+1
  amplify_auth_cognito: ^1.0.0-next.0+1
  aws_common: ^0.2.1

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  integration_test:
    sdk: flutter
  # Preprocessing.
  flutter_launcher_icons: "^0.9.2"
  flutter_native_splash: ^2.2.7

  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove
flutter_native_splash:
  android: true
  ios: true
  web: true

  color: "#232D4B"
  image: assets/icons/icon.png

  android_gravity: center
  ios_content_mode: center
  web_image_mode: center

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true
  fonts:
    - family: LibreFranklin
      fonts:
        - asset: fonts/LibreFranklin-Regular.ttf
        - asset: fonts/LibreFranklin-Bold.ttf
          weight: 700
        - asset: fonts/LibreFranklin-Italic.ttf
          style: italic
    - family: SliderFont
      fonts:
        - asset: fonts/LibreFranklin-Regular-Rotated.ttf
