name: Publish to GitHub Pages

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: nicholasphair/flutter-gh-pages@main
        with:
          workingDir: moralpain
          buildDir: ${{ steps.extract_branch.outputs.branch }}
          webRenderer: canvaskit
          baseHref: /moralpain_dev/${{ steps.extract_branch.outputs.branch }}/
